name: Call dispatcher

on:
  push:
    branches:
      - main
    paths:
      - templates/**
      - src/**
      - .github/workflows/**

jobs:
  call:
    name: Call dispatchers
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        target-repository: ${{ fromJSON(vars.TARGET_REPOSITORIES) }}
    steps:
      - name: Call dispatcher
        run: |
          gh api \
            --method POST \
            -H 'Accept: application/vnd.github+json' \
            -H 'X-GitHub-Api-Version: 2022-11-28' \
            /repos/${REPOSITORY}/dispatches \
            -f 'event_type=dispatch_readme'
        env:
          GH_TOKEN: ${{ github.token }}
          REPOSITORY: ${{ matrix.target-repository }}