name: Generate my Figura avatar README

on:
  workflow_call:
    inputs:
      branch-name:
        required: true
        type: string

jobs:
  generate:
    name: Generate my Figura avatar README
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout avatar repository
        uses: actions/checkout@v5.0.0
        with:
          path: ./avatar
          ref: ${{ inputs.branch-name }}
      - name: Checkout template repository
        uses: actions/checkout@v5.0.0
        with:
          path: ./generator
          repository: Gakuto1112/FiguraAvatarsReadmeTemplate
          ref: v1.3.0
      - name: Setup Node.js@20.8.0
        uses: actions/setup-node@v5.0.0
        with:
          node-version: 20.8.0
          cache: npm
          cache-dependency-path: ./generator/package-lock.json
      - name: Install script dependencies
        working-directory: ./generator
        run: npm install
      - name: Generate README
        working-directory: ./generator
        run: ./node_modules/.bin/ts-node ./src/readme_generator.ts ../avatar/ ${{ github.repository }}
      - id: check_diff
        name: Check diff
        working-directory: ./avatar
        continue-on-error: true
        run: |
          git add -N --all
          git diff --exit-code
      - name: Commit and push
        if: ${{ steps.check_diff.outcome == 'failure' }}
        working-directory: ./avatar
        run: |
          git remote set-url origin https://github-actions:${{ github.token }}@github.com/${{ github.repository }}
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add --all
          git commit -m '[GitHub Actions] ドキュメントの自動生成' -m '対象のコミット: ${{ github.sha }}'
          git push origin
